# Development environment, customizable configuration
eureka:
  instance:
    # Custom node registration IP
    ip-address: ${SERVICE_HOST:192.168.0.103}

spring:
  datasource:
    # Customize MySQL configuration
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/dc3?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    # Customize Rabbitmq configuration
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  redis:
    # Customize Redis configuration
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  data:
    mongodb:
      # Customize Mongo configuration
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  cache:
    redis:
      # Customize Cache configuration
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:5M}
