#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

driver:
  name: PlcS7Driver
  type: DRIVER
  project: @project.artifactId@
  remark: @project.description@
  schedule:
    status:
      enable: true
      corn: '0/10 * * * * ?'
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn: '0/5 * * * * ?'
  driver-attribute:
    - display-name: 主机
      attribute-name: host
      type: string
      value: 192.168.0.20
      remark: Ip
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - display-name: 端口
      attribute-name: port
      type: int
      value: 102
      remark: Port
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
  point-attribute:
    - display-name: DB序号
      attribute-name: dbNum
      type: int
      value: 0
      remark: 数据块号，从 0 开始计数
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - display-name: 字偏移
      attribute-name: byteOffset
      type: int
      value: 0
      remark: 字偏移
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - display-name: 位偏移
      attribute-name: bitOffset
      type: int
      value: 0
      remark: 位偏移
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - display-name: 数据块长度
      attribute-name: blockSize
      type: int
      value: 8
      remark: 数据块长度
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString

server:
  port: 8601

spring:
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/plcs7/${spring.application.name}.log