# Development environment, customizable configuration
eureka:
  instance:
    # Custom node registration ip, dedicated to the development environment
    ip-address: ${SERVICE_HOST}

# Log config
logging:
  level:
    io.github.pnoker: DEBUG
    io.github.pnoker.common.sdk: DEBUG