spring:
  security:
    user:
      name: ${SECURITY_USER_NAME:dc3}
      password: ${SECURITY_USER_PASSWORD:dc3}

eureka:
  instance:
    prefer-ip-address: true
    hostname: @project.artifactId@
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    region: dc3
    availability-zones:
      dc3: defaultZone
    prefer-same-zone-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_HOST:dc3-center-register}:${EUREKA_PORT:8100}/eureka/