gateway:
  save:
    opentsdb: true
    elasticsearch: true

auth:
  save:
    opentsdb: true
    elasticsearch: true

manager:
  save:
    opentsdb: true
    elasticsearch: true

data:
  save:
    opentsdb: true
    elasticsearch: true