#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

driver:
  tenant: default
  name: MqttDriver
  type: DRIVER
  project: @project.artifactId@
  remark: @project.description@
  schedule:
    read:
      enable: false
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn: '0/5 * * * * ?'
  point-attribute:
    - display-name: 指令Topic
      attribute-name: commandTopic
      attribute-type-flag: STRING
      default-value: commandTopic
      remark: 测点/设备接收下行指令的Mqtt主题
    - display-name: 指令Qos
      attribute-name: commandQos
      attribute-type-flag: INT
      default-value: 2
      remark: 测点/设备接收下行指令的Mqtt主题的Qos
  mqtt:
    url: tcp://127.0.0.1:1883
    auth-type: USERNAME
    username: dc3
    password: dc3
    receive-topics:
      - qos: 1
        name: driver/${spring.application.name}/device/+
    default-send-topic:
      qos: 1
      name: driver/${spring.application.name}/command
    keep-alive: 15
    completion-timeout: 3000
    batch:
      speed: ${MQTT_BATCH_SPEED:100}
      interval: ${MQTT_BATCH_INTERVAL:5}

spring:
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/mqtt/${spring.application.name}.log